name: foodie_app
description: Your Global Recipe Explorer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.1.1

  # Network & API
  http: ^1.1.0
  cached_network_image: ^3.3.0

  # Storage
  shared_preferences: ^2.2.2

  # UI Components
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4

  # Utils
  url_launcher: ^6.2.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add any assets here later
  # assets:
  #   - assets/images/

  # Add any fonts here later
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf